### ISSUE TITLE
For cycle

### ISSUE THREAD

**Issue by IanaKhitsko** [kirick1/project-technologies#7]
https://github.com/kirick1/project-technologies/blob/bffa0854a4384dc9ba3ce69e652093d298e25a06/classes/map.ts#L62-L65

Conditions in for cycle could be more simple.
for (let i = country.coordinates.xl; i < country.coordinates.xh + 1; i++)
...
(The same for j)
And you dont need x,y locals in this case

**Comment by kirick1** [comment]
Fixed, but it needs <= condition in loop
